services:
  web:
    build: ./oligostore
    container_name: oligostore_web
    command: >
      sh -c "
      npm ci &&
      npx tailwindcss -c ./tailwind.config.cjs -i ./static/css/src/styles.css -o ./static/css/dist/styles.css --minify &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./oligostore:/app
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: oligostore_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #nginx:
  #  image: nginx:latest
  #  container_name: oligostore_nginx
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./oligostore:/app
  #  depends_on:
  #    - web

volumes:
  postgres_data:
